name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: greet
      - run: echo "Hello World!"
      - name: copy_files
      - uses: actions/checkout@v3
      - name: check_files
      - run: ls -la
